/**
 * Turbo Encabulator: New Transmission Principle & Automatic Synchronization Mechanism
 * 
 * This module implements the "New Prime" (N.P.) theory derived from the legacy principles.
 * Instead of power generated by relative motion, it utilizes modulated interaction between magnetic reluctance and capacitive directance to generate torque for inertial generators and drive automatic synchronization of cardinal grammeters via harmonic resonance.

### Core Concepts & Mathematical Frameworks

1.  **The N.P. Principle**: The transmission is driven not by the vector sum of current ($\sum I$) but by a specific interaction coefficient $K_{NP}$.
    *   Current generation: $\mathbf{I}_{gen} = \frac{\phi}{R}$ (where $\phi$ is magnetic flux, $R$ is resistance).
    *   Synchronization Logic: The system calculates the "harmonic index" of the current vector. If this index matches a target harmonic ($H_{target}$), it applies an inverse reactive force to align the cardinal grammeters in phase.

2.  **Magnetic Reluctance Calculation**: Based on standard magnetic circuit theory adapted for non-linear systems (logarithmic casing).
    *   $R = \rho l + M$ (where $\rho$ is resistivity, $l$ length, and $M$ magnetization factor derived from the logarithmic casing geometry).

3.  **Capacitive Directance**: In a reactive current system with capacitors ($C_{cap}$), voltage drop across capacitance creates an opposing magnetic flux component that aids in synchronizing currents to their target harmonic frequency.
    *   $V = I \cdot X_C - I \cdot (X_L + R)$. The capacitor term opposes the reactance of conductors, aiding synchronization.

4.  **Torque Production**: $\tau_{NP} = K_{NP} \times (\text{Current Harmonic Index})^2$ to ensure robust inertia control without direct current generation failure.
    *   $K_{NP}$ is derived from the interaction coefficients of reluctance and capacitance in the specific casing geometry (e.g., "Logarithmic" implies logarithmic decrement).

5.  **Automatic Synchronization**: The `turbo_encabulator` module monitors the vector sum of all current components ($\sum \mathbf{I}$) against a target harmonic $H_{target}$. If they match, it applies an inverse reactive force to realign grammeters in phase (e.g., aligning 120-degree spaced vectors).

### Implementation Details

*   **Class-Based Winding Generator**: Uses `class` for structural clarity and easy extension.
*   **Harmonic Index Calculation**: Computes the vector sum of currents relative to a reference harmonic ($H_{ref}$) or target harmonic $H_{target}$. This is critical for determining if synchronization is needed.
*   **Inverse Reactive Force Application**: When grammeters are out-of-phase, calculates an inverse reactive force based on the difference between current and harmonics.

### Usage Example (Simplified)
